const TAG_ORDER = ['buzz', 'flame', 'ignored', 'misread', 'repost', 'bookmark', 'ai_smell'];
const TAG_LABEL = { buzz: 'バズる', flame: '炎上', ignored: 'スルー', misread: '誤解', repost: 'リポスト価値', bookmark: '保存価値', ai_smell: 'AI臭' };
const DEFAULTS = { apiKey: '', enabled: true, lang: 'ja', threshold: 0.5, maxPerMinute: 120, tags: ['buzz', 'misread', 'repost', 'bookmark', 'ai_smell'], goalPreset: 'none', goalCustom: '' };
const GOAL_LABEL = { none: '指定しない（一般的な「絡む価値」）', grow: 'フォロワーを増やしたい', learn: '学びたい', thrill: '刺激がほしい', custom: '自分で書く' };
for (const g of Object.keys(GOAL_LABEL)) { const l = document.createElement('label'); l.style.fontWeight = '400'; l.style.margin = '0'; l.innerHTML = `<input type="radio" name="goal" value="${g}"> ${GOAL_LABEL[g]}`; document.getElementById('goals').appendChild(l); }
const goalPreset = () => document.querySelector('input[name="goal"]:checked')?.value || 'none';
document.getElementById('goals').addEventListener('change', () => { document.getElementById('goalCustom').style.display = goalPreset() === 'custom' ? 'block' : 'none'; });
for (const t of TAG_ORDER) { const l = document.createElement('label'); l.style.fontWeight = '400'; l.style.margin = '0'; l.innerHTML = `<input type="checkbox" data-tag="${t}"> ${TAG_LABEL[t]}`; document.getElementById('tags').appendChild(l); }
const selectedTags = () => [...document.querySelectorAll('#tags input')].filter(i => i.checked).map(i => i.dataset.tag);
const $ = id => document.getElementById(id);
chrome.storage.sync.get(DEFAULTS, s => { $('apiKey').value = s.apiKey; $('lang').value = s.lang; $('threshold').value = s.threshold; $('maxPerMinute').value = s.maxPerMinute; $('enabled').checked = s.enabled; for (const i of document.querySelectorAll('#tags input')) i.checked = s.tags.includes(i.dataset.tag); const gr = document.querySelector(`input[name="goal"][value="${s.goalPreset}"]`); if (gr) gr.checked = true; $('goalCustom').value = s.goalCustom || ''; $('goalCustom').style.display = s.goalPreset === 'custom' ? 'block' : 'none'; });
$('save').onclick = () => chrome.storage.sync.set({ apiKey: $('apiKey').value.trim(), lang: $('lang').value, threshold: +$('threshold').value, maxPerMinute: +$('maxPerMinute').value, enabled: $('enabled').checked, tags: selectedTags(), goalPreset: goalPreset(), goalCustom: $('goalCustom').value.trim() }, () => { $('msg').textContent = '保存しました'; setTimeout(() => $('msg').textContent = '', 1500); });
$('clear').onclick = async () => { const all = await chrome.storage.local.get(null); await chrome.storage.local.remove(Object.keys(all).filter(k => k.startsWith('r:'))); $('msg').textContent = 'キャッシュを消去しました'; };
